---
- hosts: all
  become: true
  tasks:
  - name: 
    command: "subscription-manager register --force --username {{ username }} --password {{ password }}"
    retries: 3
  - name: Attach to Employee SKU Virtual Pool
    command: "subscription-manager subscribe --pool {{ pool }}"
    retries: 3
  - name: Disable all repositories
    command: "subscription-manager repos --disable='*'"
  - name: Enable RHEL repositories
    command: subscription-manager repos \
               --enable="rhel-7-server-rpms" \
               --enable="rhel-7-server-extras-rpms" \
               --enable="rhel-7-server-optional-rpms" \
               --enable="rhel-7-fast-datapath-rpms"
