---
- hosts: all
  remote_user: cloud-user
  tasks:
  - name: Copy .ssh
    copy:
      content: |
        Host rhel-74-vm-1 rhel-74-vm-2 rhel-74-vm-3 rhel-74-vm-4 rhel-74-vm-5 rhel-74-vm-6 rhel-74-vm-7
          HostName %h.k8s.home
          CanonicalizeHostname yes
          User cloud-user
        Host *.k8s.home
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
          HashKnownHosts no
          LogLevel ERROR
          CheckHostIP no
      dest: ~/.ssh/config
      mode: 0600
