---
- hosts: all
  remote_user: cloud-user
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
  - name: Reboot server
    command: shutdown -r now "Reboot triggered by Ansible"
    async: 0
    poll: 0
    ignore_errors: true
  - name: Wait for server to restart
    local_action:
      module: wait_for
      host: '{{ inventory_hostname }}'
      port: 22
      delay: 1
      timeout: 300
      sudo: false
