- hosts: nodes
  become: yes
  become_method: sudo
  tasks:
  - name: Change node log level
    lineinfile:
      dest: /etc/sysconfig/origin-node
      regexp: '^OPTIONS=--loglevel='
      line: 'OPTIONS=--loglevel={{loglevel}}'
