---
- hosts: all
  become: yes
  tasks:
  - name: Install NetworkManager
    yum: name=NetworkManager state=present
  - name: Disable network service
    systemd: name=network enabled=no
  - name: Enable NetworkManager service
    systemd: name=NetworkManager enabled=yes
