---
- hosts: all
  become: true
  tasks:
  - name: Install python-sebindings
    yum:
      name: libselinux-python
  - name: Install epel-release
    yum:
      name: epel-release
  - name: Install tuned dependencies
    yum:
      name: python3-pyudev, python-pyudev
  - name: Install python-pip
    yum:
      name: python-pip
      state: present
      enablerepo: epel
  - name: Install tuned deps
    yum:
      name: libgudev1
